apiVersion: apps/v1
kind: Deployment
metadata:
  name: torn-oc-history
  annotations:
    app.kubernetes.io/source-code: "git@github.com:mnuck/torn-oc-history.git"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torn-oc-history
  template:
    metadata:
      labels:
        app: torn-oc-history
    spec:
      securityContext:
        fsGroup: 1001
      imagePullSecrets:
      - name: ghcr-cred
      containers:
      - name: torn-oc-history
        image: ghcr.io/mnuck/torn-oc-history:latest
        command: ["/app"]
        args:
          - "--output"
          - "sheets"
          - "--interval"
          - "5m"
          - "--both"
          - "--range-noc"
          - "OC History, Truant Members (Jokerz)"
          - "--range-all"
          - "OC History, All Members (Jokerz)"
        env:
        - name: LOGLEVEL
          value: "warn"
        - name: ENV
          value: "production"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: env-file
          mountPath: /.env
          subPath: .env
          readOnly: true
        - name: credentials-file
          mountPath: /credentials.json
          subPath: credentials.json
          readOnly: true
      volumes:
      - name: env-file
        secret:
          secretName: torn-history-secrets
          items:
          - key: .env
            path: .env
      - name: credentials-file
        secret:
          secretName: torn-history-secrets
          items:
          - key: credentials.json
            path: credentials.json 