apiVersion: v1
kind: Secret
metadata:
  name: torn-history-secrets
type: Opaque
data:
  # Base64 encoded .env file content
  # cat .env | base64 -w 0
  .env: "your_base64_encoded_env_file_content_here"

  # Google Sheets credentials JSON file (base64 encoded)
  # cat credentials.json | base64 -w 0
  credentials.json: "your_base64_encoded_credentials_json_content_here" 